name: orville-postgresql-libpq
version: '0.9.0.0'
synopsis: ORM
description: ORM library for PostgreSQL
category: Database
author: Flipstone Technology Partners
maintainer: development@flipstone.com
license: MIT
git: git@github.com:flipstone/orville.git
tested-with: GHC == 7.10.3, GHC == 8.0.2, GHC == 8.2.2, GHC == 8.4.4
extra-source-files:
  - README.md
ghc-options:
  - -Wall
  - -fno-warn-orphans
  - -fwarn-incomplete-uni-patterns
  - -fwarn-incomplete-record-updates
dependencies:
  - base >=4.8 && <5
  - bytestring
  - postgresql-libpq >= 0.9.4.2 && <0.10
  - resource-pool
  - time >=1.5
  - unliftio

library:
  source-dirs: src
  exposed-modules:
    - Database.Orville.PostgreSQL.Connection
